# 🧪 Pandas Wrangle Lab: Clean & Explore a Real Dataset

## 🔹 LEARNING GOALS:
- Practice loading, cleaning, and exploring real-world data
- Apply column creation, renaming, sorting, and filtering
- Use `.info()`, `.describe()`, and `.query()` fluently

### 📥 1. Load the Dataset

In [2]:
import pandas as pd

data = {
    "first_name": ["Danielle", "Angel", "Joshua", "Jeffrey", "Jill"],
    "last_name": ["Wood", "Clark", "Adams", "Zuniga", "Wong"],
    "math_score": [100, 67, 61, 77, 75],
    "science_score": [95, 78, 100, 99, 83]
}

df = pd.DataFrame(data)
df.head()

  first_name last_name  math_score  science_score
0   Danielle      Wood         100             95
1      Angel     Clark          67             78
2     Joshua     Adams          61            100
3    Jeffrey    Zuniga          77             99
4       Jill      Wong          75             83

### 🔎 2. Inspect and Audit the Data

In [3]:
# Basic overview
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 4 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   first_name     5 non-null      str
 1   last_name      5 non-null      str
 2   math_score     5 non-null      int64
 3   science_score  5 non-null      int64
dtypes: int64(2), str(2)
memory usage: 292.0 bytes

In [4]:
# Summary stats
df.describe()

       math_score  science_score
count    5.000000       5.000000
mean    76.000000      91.000000
std     14.866069       9.924717
min     61.000000      78.000000
25%     67.000000      83.000000
50%     75.000000      95.000000
75%     77.000000      99.000000
max    100.000000     100.000000

### 🧼 3. Clean Missing or Invalid Data

In [5]:
# Check for missing values
df.isnull().sum()

first_name       0
last_name        0
math_score       0
science_score    0
dtype: int64

In [6]:
# Drop rows with missing names
df.dropna(subset=["first_name", "last_name"], inplace=True)

# Fill any missing scores with column average
df["math_score"].fillna(df["math_score"].mean(), inplace=True)
df["science_score"].fillna(df["science_score"].mean(), inplace=True)

C:\Users\andre\AppData\Local\Temp\ipykernel_24404\210016614.py:5: ChainedAssignmentError: A value is being set on a copy of a DataFrame or Series through chained assignment using an inplace method.
Such inplace method never works to update the original DataFrame or Series, because the intermediate object on which we are setting values always behaves as a copy (due to Copy-on-Write).

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' instead, to perform the operation inplace on the original object, or try to avoid an inplace operation using 'df[col] = df[col].method(value)'.

See the documentation for a more detailed explanation: https://pandas.pydata.org/pandas-docs/stable/user_guide/copy_on_write.html
  df["math_score"].fillna(df["math_score"].mean(), inplace=True)
C:\Users\andre\AppData\Local\Temp\ipykernel_24404\210016614.py:6: ChainedAssignmentError: A value is being set on a copy of a DataFrame or Series through chained assignment using an inplace method.
Such inplace method never works to update the original DataFrame or Series, because the intermediate object on which we are setting values always behaves as a copy (due to Copy-on-Write).

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' instead, to perform the operation inplace on the original object, or try to avoid an inplace operation using 'df[col] = df[col].method(value)'.

See the documentation for a more detailed explanation: https://pandas.pydata.org/pandas-docs/stable/user_guide/copy_on_write.html
  df["science_score"].fillna(df["science_score"].mean(), inplace=True)

0     95
1     78
2    100
3     99
4     83
Name: science_score, dtype: int64

### 🧠 4. Feature Engineering (New Columns)

In [7]:
# Add average and grade
df["average_score"] = (df["math_score"] + df["science_score"]) / 2

def grade(score):
    if score >= 90:
        return "A"
    elif score >= 80:
        return "B"
    elif score >= 70:
        return "C"
    else:
        return "D"

df["grade"] = df["average_score"].apply(grade)
df.head()

  first_name last_name  math_score  science_score  average_score grade
0   Danielle      Wood         100             95           97.5     A
1      Angel     Clark          67             78           72.5     C
2     Joshua     Adams          61            100           80.5     B
3    Jeffrey    Zuniga          77             99           88.0     B
4       Jill      Wong          75             83           79.0     C

### 🔽 5. Sorting and Filtering

In [8]:
# Top performers
df[df["average_score"] > 90].sort_values(by="average_score", ascending=False).head()

  first_name last_name  math_score  science_score  average_score grade
0   Danielle      Wood         100             95           97.5     A

### 📊 6. Group and Describe by Grade

In [9]:
# How many of each grade?
df["grade"].value_counts()

grade
C    2
B    2
A    1
Name: count, dtype: int64

In [10]:
# Average scores per grade group
df.groupby("grade")[["math_score", "science_score", "average_score"]].mean()

       math_score  science_score  average_score
grade
A           100.0           95.0          97.50
B            69.0           99.5          84.25
C            71.0           80.5          75.75

### 💾 7. Save the Cleaned Dataset

In [11]:
df.to_csv("student_scores_cleaned.csv", index=False)

### 🧠 Challenge Task

> Your turn! Filter out students who got a D, sort by last name, and export to a new file:
- Only include columns: `first_name`, `last_name`, `grade`
- Save it as `"d_students.csv"`

In [12]:
# Filter students with grade D
d_students = df[df["grade"] == "D"]

# Sort by last name
d_students = d_students.sort_values(by="last_name")

# Only keep these columns
d_students = d_students[["first_name", "last_name", "grade"]]

# Save to CSV
d_students.to_csv("d_students.csv", index=False)

# Show result
d_students

Empty DataFrame
Columns: [first_name, last_name, grade]
Index: []

### 📝 Summary

This lab gave you hands-on experience with:
- Cleaning nulls and type mismatches
- Creating new columns
- Filtering and sorting real data
- Grouping and summarizing by categorical features

Your data wrangling toolbox is now ready for real-world messiness. 🧹🛠️